package com.quizocr.vitesse.ui.addEditCandidate

import android.util.Log
import androidx.lifecycle.SavedStateHandle
import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewModelScope
import com.quizocr.vitesse.domain.model.Candidate
import com.quizocr.vitesse.domain.usecase.GetCandidateById
import com.quizocr.vitesse.domain.usecase.AddNewCandidateUseCase
import com.quizocr.vitesse.data.repository.DataResult
import com.quizocr.vitesse.domain.usecase.UpdateCandidateUseCase
import dagger.hilt.android.lifecycle.HiltViewModel
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.flow.launchIn
import kotlinx.coroutines.flow.onEach
import kotlinx.coroutines.flow.onStart
import kotlinx.coroutines.flow.update
import kotlinx.coroutines.launch
import java.time.LocalDate
import javax.inject.Inject

@HiltViewModel
class AddEditCandidateViewModel @Inject constructor(
    private val getCandidateById: GetCandidateById,
    private val addCandidateUseCase: AddNewCandidateUseCase,
    private val updateCandidateUseCase: UpdateCandidateUseCase,
    savedStateHandle: SavedStateHandle
) : ViewModel() {

    private val _uiState = MutableStateFlow(AddEditCandidateUiState())
    val uiState: StateFlow<AddEditCandidateUiState> = _uiState.asStateFlow()
    val candidateId: Int = savedStateHandle.get<Int>("candidateId") ?: -1

    init {
        val screenTitle: String = savedStateHandle.get<String>("screenTitle") ?: ""
        _uiState.update { it.copy(screenTitle = screenTitle) }

        if (candidateId != -1) {
            loadCandidateDetails(candidateId)
        }
    }

    private fun loadCandidateDetails(id: Int) {
        getCandidateById.execute(id)
            .onStart { _uiState.update { it.copy(isLoadingCandidateData = true) } }
            .onEach { result ->
                when (result) {
                    is DataResult.Success -> _uiState.update {
                        it.copy(
                            candidate = result.data,
                            isLoadingCandidateData = false,
                            errorMessage = null
                        )
                    }
                    is DataResult.Error -> _uiState.update {
                        it.copy(
                            isLoadingCandidateData = false,
                            errorMessage = result.exception.message ?: "Failed to load candidate"
                        )
                    }
                }
            }
            .launchIn(viewModelScope)
    }

    fun saveCandidate(
        firstName: String,
        lastName: String,
        phoneNumber: String,
        email: String,
        dateOfBirth: LocalDate,
        salary: Double?,
        notes: String?,
        photoUri: String?
    ) {
        viewModelScope.launch {
            _uiState.update { it.copy(isSaving = true, saveSuccess = false, errorMessage = null) }

            val candidateToSave: Candidate = if (candidateId != -1) {
                _uiState.value.candidate?.copy(
                    firstName = firstName,
                    lastName = lastName,
                    phoneNumber = phoneNumber,
                    email = email,
                    dateOfBirth = dateOfBirth,
                    salaryEuros = salary ?: 0.0,
                    notes = notes,
                    photoUri = photoUri,
                    updatedAt = System.currentTimeMillis()
                ) ?: return@launch // Should not happen if candidate is loaded for an edit
            } else {
                Candidate(
                    id = 0, // ID is 0 for a new candidate, will be auto-generated by the DB
                    firstName = firstName,
                    lastName = lastName,
                    phoneNumber = phoneNumber,
                    email = email,
                    dateOfBirth = dateOfBirth,
                    salaryEuros = salary ?: 0.0,
                    notes = notes,
                    photoUri = photoUri,
                    isFavorite = false,
                    createdAt = System.currentTimeMillis(),
                    updatedAt = System.currentTimeMillis()
                )
            }

            val result = if (candidateId != -1) {
                updateCandidateUseCase.execute(candidateToSave)
            } else {
                addCandidateUseCase.execute(candidateToSave)
            }

            when (result) {
                is DataResult.Success -> {
                    _uiState.update { currentState ->
                        currentState.copy(
                            isSaving = false,
                            saveSuccess = true,
                            candidate = if (candidateId != -1) candidateToSave else currentState.candidate
                        )
                    }
                }
                is DataResult.Error -> {
                    _uiState.update {
                        it.copy(
                            isSaving = false,
                            errorMessage = result.exception.message ?: "Save operation failed"
                        )
                    }
                }
            }
        }
    }

    fun clearErrorMessage() {
        _uiState.update { it.copy(errorMessage = null) }
    }
}
